### ISSUE TITLE
Particle area - Glow squid does not spawn when clicking the Squid Ink sign

### ISSUE THREAD

**Issue by Celesian** [kcrca/restworld#1]
Steps to Reproduce: 

1. Open Restworld + travel to particle area
2. Click the  Squid Ink  sign

 
Observed Results: 
A glow squid does not spawn

Expected Results: 

A glow squid should spawn 
 
Screenshots/Videos: 

[https://streamable.com/sryra1](https://streamable.com/sryra1) 
 
Notes: 
Using Restworld 1.17.1

**Comment by Celesian** [comment]
I unfortunately don't see even a normal squid spawning. And yes both squids would be great! Thank you

**Comment by kcrca** [comment]
I've tried this out in 1.17, and found that there was a few seconds' lag in the squid showing up. Did you wait for that amount of time?

I know that in the upcoming RestWorld release I fixed the "presence" detection for the particle room, and in that version there is no log, and it loops between them.

Can you try (a) just waiting longer, and/or (b) leaving the room and coming back in a few times, at a normal pace, and tell me what happens for you? Thanks!

**Comment by Celesian** [comment]
Tried both no luck

**Comment by kcrca** [comment]
Can you try downloading https://claritypack.com/restworld/RestWorld_1.17.1_a.zip and giving that a try? It's my current work-in-progress version, and it definitely works for me.

**Comment by kcrca** [comment]
Also, I'd be curious if there is a problem with other creature-based ones, like spit or hearts?

**Comment by kcrca** [comment]
Ah, one other thing: Is the clock running?

**Comment by Celesian** [comment]
Its working now (the squids, on the 1.17.1_a version) the other creature based ones don't have any issue. Thank you for fixing this
